### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by issakomi** [neurolabusc/dcm_qa_12bit#1]
> These are identified as 12 Bits Allocated (0028,0100). Curiously, the DICOM standard requires Bits Stored shall either be 1, or a multiple of 8.

_Bits Allocated_ and _Bits Stored_ seem to be swapped here. Such images are identified by _Bits Allocated_ = 16 and _Bits Stored_ = 12.

![Screenshot 2023-03-09 at 08-04-36 C 7 6 3 3 Image Pixel Description Macro](https://user-images.githubusercontent.com/1494580/224278045-b61173f2-3bfc-48d3-9b94-0691dd6e4044.png)

Thanks for the examples!

**Comment by neurolabusc** [comment]
Thanks
